camunda.bpm:
  authorization:
    enabled: true


plugin.identity.keycloak:
  keycloakIssuerUrl: http://localhost:8080/realms/master
  keycloakAdminUrl: http://localhost:8080/admin/realms/master
  clientId: camunda-identity-service
  clientSecret: 42aa42bb-1234-4242-a24a-42a2b420cde0
  useEmailAsCamundaUserId: true
  administratorGroupName: camunda-admin

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: camunda-identity-service
  credentials:
    secret: 42aa42bb-1234-4242-a24a-42a2b420cde0




# Spring Boot Security OAuth2 SSO
spring.security.oauth2:
  client:
    registration:
      keycloak:
        provider: keycloak
        client-id: camunda-identity-service
        client-secret: AzuFdqTK7qdUKCuwU5SdWDNE6KQ2WV9z
        authorization-grant-type: authorization_code
        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        scope: openid, profile, email
    provider:
      keycloak:
        issuer-uri: http://localhost:8080/realms/master
        authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth
        user-info-uri: http://localhost:8080/realms/master/protocol/openid-connect/userinfo
        token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
        jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
        # set user-name-attribute one of:
        # - sub                -> default; using keycloak ID as camunda user ID
        # - email              -> useEmailAsCamundaUserId=true
        # - preferred_username -> useUsernameAsCamundaUserId=true
        user-name-attribute: preferred_username